import FullScreenSection from "../shared/FullScreenSection.tsx";
import { Avatar, Button, Heading, Link, Text } from "@chakra-ui/react";
import { projectName, bio } from "./constants.ts";
import { useState } from "react";

const LandingSection = () => {
  const [backgroundColor, setBackgroundColor] = useState("rgba(215, 146, 68, 0.3)");

  const getRandomBackgroundColor = () => {
    return `rgba(${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)}, 0.3)`;
  };

  const handleRandomBackgroundColor = () => {
    setBackgroundColor(getRandomBackgroundColor());
  };

  return (
    <FullScreenSection
      justifyContent="center"
      alignItems="center"
      isDarkBackground
      background={`linear-gradient(to bottom, ${backgroundColor}, #181818)`}
    >
      <Avatar.Root shape="full" size="2xl" width="100px" height="100px">
        <Avatar.Fallback name="Random Avatar" />
        <Avatar.Image src="https://i.pravatar.cc/" />
      </Avatar.Root>

      <Text fontSize="xs" my="10px">
        Generated by <Link href="https://i.pravatar.cc/" target="_blank" rel="noopener noreferrer">https://i.pravatar.cc/</Link>
      </Text>

      <Heading fontSize="2xl" fontWeight="bold">
        {projectName}
      </Heading>
      
      <Text fontSize="md" marginBottom="15px">
        {bio}
      </Text>

      <Button onClick={handleRandomBackgroundColor}>
        Random background coloring 😊
      </Button>
    </FullScreenSection>
  );
}

export default LandingSection;
